Repository domWalters/mkdocs-to-pdf, pull requests merged in 2025-03, with the labels that each got.

#40 chore: increment pymdown-extensions from 10.4 to 10.14.3
  .gitignore
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  uv.lock
Labels: bug

#44 feat: integrate an experimental PDF download link using the download_link option #25
  README.md
  samples/material/download_link/docs/index.md
  samples/material/download_link/mkdocs.yml
  src/mkdocs_to_pdf/drivers/event_hook.py
  src/mkdocs_to_pdf/options.py
  src/mkdocs_to_pdf/themes/material.py
  src/mkdocs_to_pdf/themes/mkdocs.py
Labels: enhancement

#45 docs: rewrite all documentation
  .pre-commit-config.yaml
  .readthedocs.yaml
  CHANGELOG
  LICENSE
  Makefile
  README.md
  docs/CHANGELOG.md
  docs/LICENSE.md
  docs/README.md
  docs/examples/admonitions.md
  docs/examples/annotations.md
  docs/examples/basics.md
  docs/examples/blockquotes.md
  docs/examples/buttons.md
  docs/examples/cjk-fonts.md
  docs/examples/code-blocks.md
  docs/examples/content-tabs.md
  docs/examples/data-tables.md
  docs/examples/download-link.md
  docs/examples/footnotes.md
  docs/examples/formatting.md
  docs/examples/grids.md
  docs/examples/icons-emojis.md
  docs/examples/images.md
  docs/examples/lists.md
  docs/examples/tooltips.md
  docs/installation.md
  docs/stuff-to-migrate.md
  docs/stylesheets/extra.css
  docs/usage.md
  mkdocs.yml
  pyproject.toml
  requirements-dev.txt
  samples/material/Makefile
  samples/material/admonitions/mkdocs.yml
  samples/material/annotations/mkdocs.yml
  samples/material/basics/mkdocs.yml
  samples/material/blockquotes/mkdocs.yml
  samples/material/buttons/mkdocs.yml
  samples/material/cjk_fonts/mkdocs.yml
  samples/material/code_blocks/mkdocs.yml
  samples/material/content_tabs/mkdocs.yml
  samples/material/data_tables/mkdocs.yml
  samples/material/download_link/mkdocs.yml
  samples/material/footnotes/mkdocs.yml
  samples/material/formatting/mkdocs.yml
  samples/material/grids/mkdocs.yml
  samples/material/icons_emojis/mkdocs.yml
  samples/material/images/mkdocs.yml
  samples/material/lists/mkdocs.yml
  samples/material/tooltips/mkdocs.yml
  uv.lock
Labels: documentation

#56 feat: add more to pre-commit, add cSpell configuration
  .cspell.json
  .gitattributes
  .pre-commit-config.yaml
  .vscode/settings.json
  custom_style_src/material-polyfills/.browserslistrc
  custom_style_src/material-polyfills/.editorconfig
  custom_style_src/material-polyfills/.eslintrc.js
  custom_style_src/material-polyfills/.gitattributes
  custom_style_src/material-polyfills/.gitignore
  custom_style_src/material-polyfills/.prettierrc
  custom_style_src/material-polyfills/.stylelintrc
  custom_style_src/material-polyfills/dev-site/assets/creating-your-site.png
  custom_style_src/material-polyfills/dev-site/assets/css/extra.css
  custom_style_src/material-polyfills/dev-site/assets/search-highlighting.png
  custom_style_src/material-polyfills/dev-site/assets/stylesheets/main.4dd2dd8d.min.css
  custom_style_src/material-polyfills/dev-site/assets/stylesheets/main.4dd2dd8d.min.css.map
  custom_style_src/material-polyfills/dev-site/assets/stylesheets/overrides.2b41d529.min.css
  custom_style_src/material-polyfills/dev-site/assets/stylesheets/overrides.2b41d529.min.css.map
  custom_style_src/material-polyfills/dev-site/assets/stylesheets/palette.6a5ad368.min.css
  custom_style_src/material-polyfills/dev-site/assets/stylesheets/palette.6a5ad368.min.css.map
  custom_style_src/material-polyfills/dev-site/index.html
  custom_style_src/material-polyfills/package-lock.json
  custom_style_src/material-polyfills/package.json
  custom_style_src/material-polyfills/src/javascripts/converter/twemoji.ts
  custom_style_src/material-polyfills/src/javascripts/index.ts
  custom_style_src/material-polyfills/src/stylesheets/_config.scss
  custom_style_src/material-polyfills/src/stylesheets/extensions/_admonition.scss
  custom_style_src/material-polyfills/src/stylesheets/extensions/_footnotes.scss
  custom_style_src/material-polyfills/src/stylesheets/extensions/pymdown/_details.scss
  custom_style_src/material-polyfills/src/stylesheets/extensions/pymdown/_tasklist.scss
  custom_style_src/material-polyfills/src/stylesheets/main/_typeset.scss
  custom_style_src/material-polyfills/src/stylesheets/polyfills.scss
  custom_style_src/material-polyfills/src/stylesheets/utilities/_convert.scss
  custom_style_src/material-polyfills/tsconfig.json
  custom_style_src/material-polyfills/typings/webpack-modules.d.ts
  custom_style_src/material-polyfills/webpack.config.ts
  docker/mkdocs-with-pdf/alpine/fonts/Gentium-Book-Basic/OFL.txt
  docker/mkdocs-with-pdf/alpine/fonts/MathJax/convert.py
  docker/mkdocs-with-pdf/debian/fonts/Gentium-Book-Basic/OFL.txt
  docs/examples/basics.md
  docs/examples/formatting.md
  docs/examples/icons-emojis.md
  docs/examples/images.md
  docs/usage.md
  src/mkdocs_to_pdf/preprocessor/links/transform.py
  src/mkdocs_to_pdf/templates/filters/barcode.py
  src/mkdocs_to_pdf/toc.py
  src/mkdocs_to_pdf/utils/emoji_util.py
  src/mkdocs_to_pdf/utils/image_util.py
Labels: cleanup
